{% set name = "earthformer" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/earthformer-{{ version }}.tar.gz
  sha256: 49e35e1cc8d6baa5125e6e01572618e2453548e23a9f171db4a0ee2f220f0091

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - boto3
    - botocore
    - earthnet
    - einops >=0.3.0
    - h5py >=2.10.0
    - matplotlib-base
    - nvidia-apex
    - omegaconf
    - netcdf4
    - opencv
    - pandas
    - pytorch
    - regex
    - requests
    - scipy
    - tensorboard
    - pytorch-lightning ==1.7.7
    - torchvision
    - tqdm
    - transformers >=4.3.0
    - xarray
    # additional dependencies
    # - contextvars
    # - fairscale
    - absl-py
    - awscli
    - einops
    # - fvcore
    - graphviz
    - jsonlines
    - networkx
    - pympler
    - protobuf
    - pyarrow
    - timm
    - unidiff
    - yacs
    - leafmap
    - localtileserver
    - geopandas

test:
  imports:
    - earthformer
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/opengeos/earthformer
  summary: A Python package for Earth forecasting transformer (Earthformer)
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - giswqs
